name: validate

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '22', '24', '26' ]
    name: Node ${{ matrix.node }} test
    steps:
      # https://github.com/actions/checkout/releases/tag/v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Setup node
      # https://github.com/actions/setup-node/releases/tag/v7.0.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linter
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test
